# RT URL, e.g. "http://support.company.com/rt"
# No trailing /
rt = "https://demo.bestpractical.com"

# RT credentials (guest works for the demo site)
user = "guest"
pass = "guest"

# Verify SSL - for sites with bad certs
sslverify = true
